### ISSUE TITLE
Bug: Long results escape the chat message card

### ISSUE THREAD

**Issue by BrotherSharper** [jsinme/fvtt-bcdice#10]
![image](https://user-images.githubusercontent.com/41280723/109933136-6c9a5580-7d0e-11eb-952f-4f9a236557ea.png)
As with the image above, that is an extreme example, but some systems have exploding dies built-in which may yield a long string of results. These results cause the chat card to not wrap the result and thus resulting in the string going beyond the side of the card

**Comment by jsinme** [comment]
Should be fixed. Wrapping was not occurring due to no spaces between digits and commas. Added No Width Whitespaces to string to allow for word wrap opportunities.
