### ISSUE TITLE
Bug: Some commands escape special characters when sent to API

### ISSUE THREAD

**Issue by BrotherSharper** [jsinme/fvtt-bcdice#12]
## What is happening
Using BCDice as system, try inputting 2d6+1>=5
Result: (2D6) ＞ 5[2,3] ＞ 5
Expected result: (2D6+1>=5) ＞ 5[2,3]+1 ＞ 6 ＞ 成功

## Cause
In the following code, commands are being sent to the API as-is and are not accounting for character escaping.
https://github.com/jsinme/fvtt-bcdice/blob/0.2.2-beta/scripts/bcdice.js#L86

Frequently used characters in BCDice: <>=!@#$[]() etc.

URLSearchParam could help you in fixing this.

**Comment by jsinme** [comment]
Should be fixed. Will be included in next release. a977c5fe6a3ed763629932577178eeafabd5477b
