### ISSUE TITLE
[High] Feature request: Message formatting redux

### ISSUE THREAD

**Issue by BrotherSharper** [jsinme/fvtt-bcdice#15]
Related to #4 
In order to show who did the roll please format the message as following:

```
Player name:
Command output

BCDice (Game System Name):
Command Result
```

The purpose is twofold, show who did the roll, and distinguish between a command that would have the same name but different output depending on the selected system.

**Comment by jsinme** [comment]
I believe this is in line with what was requested. Please close this issue if the formatting is fine or add additional details on how to update it.

**Comment by BrotherSharper** [comment]
Thank you!
Could the Player part and the BC dice part be split into two message cards?
Possibly with the player one being created as a chat message from that player, so that modules that alter chat card color based on the player can change it and make it distinguishable
