### ISSUE TITLE
Bug: Dice rolling audio does not play

### ISSUE THREAD

**Issue by BrotherSharper** [jsinme/fvtt-bcdice#16]
Below is the error from the console:
![image](https://user-images.githubusercontent.com/41280723/109954810-1dabea80-7d25-11eb-8d04-e9b4cfa77868.png)
![image](https://user-images.githubusercontent.com/41280723/109954822-213f7180-7d25-11eb-930d-8c0448da843d.png)

**Comment by jsinme** [comment]
Should be fixed. c9ab68e19fe70ce82286c9cc20408d9fc0b75c79
Does the dice roll sound need to be played just for the person rolling or for everyone at the session?

**Comment by BrotherSharper** [comment]
> 
> 
> Should be fixed. [c9ab68e](https://github.com/jsinme/fvtt-bcdice/commit/c9ab68e19fe70ce82286c9cc20408d9fc0b75c79)
> Does the dice roll sound need to be played just for the person rolling or for everyone at the session?

Thank you for the fix!
Sound should play for everyone (mostly helps the GM understand when a roll was made as the person doing the roll is well aware of it)

**Comment by jsinme** [comment]
With DSN, I've set up synchronicity so that the dice should roll for everyone. In the case that DSN is not installed or not enabled for a user, it will post a message that plays a dice sound for everyone.
