### ISSUE TITLE
[High] QoL: Change the system search to be friendly for foreign languages

### ISSUE THREAD

**Issue by BrotherSharper** [jsinme/fvtt-bcdice#18]
The current dropdown turns out to be a bit weird to use with Japanese keyboards as the inputs do not directly allow you to search that.
I would want to suggest making some sort of dropdown but with autocomplete search? Or just a search bar really, whichever is easier to implement

**Comment by jsinme** [comment]
Added search functionality d44a6c75c7fbe7dca44888d51d6db0a38d01705f
