### ISSUE TITLE
Pop out menu QoL

### ISSUE THREAD

**Issue by BrotherSharper** [jsinme/fvtt-bcdice#2]
- Keep the menu on the screen even after the roll button is pressed. The intent is that BC dice is supposed to replace the original dice roller. Perhaps make it a user/GM setting? either way this should be on by default as it is expected behavior from a standard Japanese user that the menu stays on screen.
- Shortcut key combination to bring up the roller menu and autofocus on the message box ready to type. Perhaps add another key combination such as Shift+Enter to send the command to BC dice, close the menu and return to the default FVTT chat (mostly used for text games, which are prevalent in Japan)

**Comment by jsinme** [comment]
I've made the dialog persistent so it won't close after a roll. cea6561c77515eb3cdd06137bf7661712f8c9143

**Comment by jsinme** [comment]
Added keybinding "Ctrl+Shift+B" to launch Roller. d7636b538eb60516d27b8c2a9f0e8a12ee780e6e
Added autofocus on input field and "Shift+Enter" keybinding to submit roll, close Roller, and focus chat. a578af5b4062b9f055c8b745ca8415126c867164

Split out two separate issues: #5 and #6
