### ISSUE TITLE
[Low] Feature Request: Turn message into a self roll when using secret command

### ISSUE THREAD

**Issue by BrotherSharper** [jsinme/fvtt-bcdice#21]
On any BCDice system roll, if somebody adds an `S` in front of the command such as `s3d6` then the API message receives a `secret` flag set to true. In this instance, make foundry output the messages as self rolls (only visile to the roller).

**Comment by jsinme** [comment]
Added support a93d1064abf8cbbc263b98e61de9136f3d2f97ae
