### ISSUE TITLE
Awareness QoL

### ISSUE THREAD

**Issue by BrotherSharper** [jsinme/fvtt-bcdice#3]
FVTT's chat messages are quite instant, it is often hard to spot whether something was rolled. I would like to propose either of the following to fix that:
- Add Dice So Nice support. The result returned from BC dice 90% of the cases often involve an n-sided die alongside the result, it should be possible to create a new dice so nice roll by giving these two values to it.
- Add a sound file to be played when bc dice is used. Attached below is a royalty-free, free-to-use sound often used in other Japanese VTTs. Taken from this site (https://commons.nicovideo.jp/material/nc42340 ), it does not need crediting and can be distributed as part of the module.
[nc42340.zip](https://github.com/jsinme/fvtt-bcdice/files/6027985/nc42340.zip)
- Change the color of the chat message to something identifiable.

**Comment by jsinme** [comment]
Added a sound for now. Please open up another issue for Dice So Nice.
