### ISSUE TITLE
Include the original command on the chat result

### ISSUE THREAD

**Issue by BrotherSharper** [jsinme/fvtt-bcdice#4]
Currently, if I type something such as "1d100 This is my Skill Roll", the strings get discarded and only the command goes through. Please make it so the chat card includes both the original command and the command result. This is so that others can see if there is extra text appended to the command for ease of understanding the roll intent and also understand if the user used a special command (for example, Cthulhu's CC command which rolls a d100)

**Comment by jsinme** [comment]
Implemented. The original command is shown under the result:
Ex:
(1D100) ＞ 85
Command: 1d100 Example Roll

If you'd prefer a different format, please open a new issue.
