### ISSUE TITLE
[Medium] Bug: Reload when closing guide

### ISSUE THREAD

**Issue by BrotherSharper** [jsinme/fvtt-bcdice#9]
With the following steps, the current FVTT instance ends up reloading:
- Open BC dice window
- Open any system's guide
- Close the system's guide
- Type a command (even a wrong one) and hit enter, game reloads

**Comment by jsinme** [comment]
I've spent too many hours on this bug so I've just decided to work around it. The System Help will now be output as a chat message instead of another dialog. If the dialog format is highly requested, I'll spend some more time trying to get it to work.
